### ISSUE TITLE
Update code of conduct (first-timers-only)

### ISSUE THREAD

**Issue by cg-cnu** [DAVFoundation/api_doc#2]
## first-timers-only

This issue is tagged :octocat: **first-timers-only**. It is only for people who have never contributed to open source before and are looking for an easy way take their first steps.

Consider this as your chance to dip your toe into the world of open-source and get some bragging rights for writing code that makes drones fly, cars find charging stations, helps people and goods move from place to place and more...

Find more **first-timers-only** issues from DAV Foundation [here](https://github.com/search?q=org%3ADAVFoundation+is%3Aissue+is%3Aopen+label%3Afirst-timers-only).

Thank you for your help :heart:

## What is this project?

DAV (Decentralized Autonomous Vehicles) is a new non-profit foundation working to build an open-source infrastructure for autonomous vehicles (cars, drones, trucks, robots, and all the service providers around them) to communicate and transact with each other over blockchain.

As an organization that believes in building a large community of open-source contributors, we often create issues like this one to help people take their first few steps into the world of open source.

### API DOC

The DAV project you are looking at is API DOC. This project is the API documentation for DAV's communication protocols and smart contracts.

### The Issue

Please change the file `CODE_OF_CONDUCT.md` to `code_of_conduct.md` to maintain consistency with other DAV projects. Please update the document with `tal@dav.network` instead of the `hello@lord.io` email address.

### Contributing to API DOC

- [ ] Make sure this issue is labeled `up-for-grabs` and not labeled `claimed`, to verify no one else is working on it.
- [ ] Comment in this issue that you would like to do it.
- [ ] Open the [API DOC GitHub page](https://github.com/DAVFoundation/api_doc) and click the ★ Star and then ⑂ Fork buttons.
- [ ] Clone a copy to your local machine with `$ git clone git@github.com:YOUR-GITHUB-USER-NAME/api_doc.git`
- [ ] **Modify the code_of_conduct.md file**
- [ ] Once you've made sure all your changes work correctly and committed all your changes, push your local changes back to github with `$ git push -u origin master`
- [ ] Visit your fork on GitHub.com ([https://github.com/YOUR-USER-NAME/api_doc](https://github.com/YOUR-USER-NAME/api_doc)) and create a pull request for your changes.
- [ ] Make sure your pull request describes exactly what you changed and references this issue (include the issue number in the title like this: `#5`)
- [ ] Please do not fix more than one issue at a time. Your pull request should only fix what is described in this issue.

### Asking for help

We appreciate your effort in taking the time to work on this issue and help out the open source community and the foundation. 
If you need any help, feel free to ask below or in our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). We are always happy to help 😄

**Comment by Justme764** [comment]
@cg-cnu I will take if still available.

**Comment by Justme764** [comment]
I checked and it is available im gonna do it.  hope this is ok.  happy new year!!!!

**Comment by Justme764** [comment]
I have completed and sent pr.  thanks

**Comment by cg-cnu** [comment]
Hey @Justme764 I marked the issue as claimed. I didn't see any pr being raised. Can you double check it please. Let me know if you need any help 🙂 

Wish you a happy new year 🎆

**Comment by Justme764** [comment]
@cg-cnu  I read the below statement when I went to do the PR so I put it in that branch.  I see it under "lord/slate" well at least I think I do.  I guess the fix is to moved PR to the original show branch? if so how do I do that?  Thanks for any help.

**Comment by cg-cnu** [comment]
Hi @Justme764,

Thanks for taking on so many issues in other repos!

We create these *first-timer-only* issues as a way for people who have never contributed to open-source to try their first pull request.

It actually takes a lot more time to write these issues than it would have for us to simply solve them ourselves, but we do that as a way to give many new people a chance to get involved with open source for the first time.

And I think this method works great as a way to make open-source more inviting. It has obviously succeeded in giving you a lot of enthusiasm to contribute😃 

Unfortunately, when you work on many issues at once like this, we are missing out on an opportunity for many other people to make their first ever pull request.

As I mentioned, these issues are not about solving a hard programming challenge, but about doing something new for the first time. The programming challenge here is nothing for you, and you have already contributed in the past, so why not move up to the next level now? Find an issue that isn't marked for *first-timers-only*, or find something which you think needs improving, and help us with that.

So, we going to work together on merging this particular issue to the master. You will see me closing your pull requests in other branches and making those issues available for other to pick up. Thank you again for the enthusiasm, and spending time on helping. We really do appreciate it, and I hope you understand our situation here.

**Comment by Justme764** [comment]
@cg-cnu  got ya.  sorry.  what would my next level be?  I'm new to coding but want to learn.  Thanks for your help.

**Comment by cg-cnu** [comment]
Thanks for understanding @Justme764 Really appreciate it. Lets fix this issue first and then you can start out on helping write some test cases. Before that can you create a fresh pr fixing this issue ? 

Just update the code_of_conduct file as mentioned and do a fresh commit and a pull request. 
Will merge that one to the master branch and celebrate success 🎆 Thanks!

**Comment by Justme764** [comment]
@cg-cnu ok  missed this message

**Comment by cg-cnu** [comment]
@Justme764 Lets talk here. I understand the concern you mentioned in the pull request. 
There will be a way to just do a pr for the existing commit you have already done but it might be a little tricky to explain and for you to get it right the first time. What I would suggest otherwise is to delete your `fork` on `github` and the fork it again. This time clone it afresh and fix the issue and do the pr.

Hope its clear!

**Comment by Justme764** [comment]
@cg-cnu  got ya

**Comment by Justme764** [comment]
@cg-cnu  I deleted the fork. re forked and cloned to desktop. (Don't have a key yet to do it command line or at least I think that is he problem.) I made the changes now for the PR.  How do I start the PR?  I have done them before but don't want to put it in the wrong branch this time.

**Comment by Justme764** [comment]
@cg-cnu  I believe I figured it out.  you should now see a PR.  let me know if I have done it wrong. Thanks for all you help.

**Comment by Justme764** [comment]
@cg-cnu  thanks for all your help and getting me started.  what is my next step to learn more?

**Comment by cg-cnu** [comment]
Congratulations @Justme764 🎉 🎆 👏 It was amazing that you figured out the process. Let me tell you its not easy to do, but you did it. Hope now you got the basic understanding of git and the workflow to make a pull request. We wish to see you contributing more to opensource. Feel free to join our [gitter channel](https://gitter.im/DAVFoundation/DAV-Contributors). Have a great year ahead 🙂

**Comment by cg-cnu** [comment]
@Justme764 Since you are still figuring out, I will suggest you to pick up one more first-timers and do the process from start again. This will help you solidify the concepts you learn. But, this time in a different project. Feel free to comment there if you would like to work on it. https://github.com/DAVFoundation/community-client/issues/16
