### ISSUE TITLE
Rename cli file to index.html

### ISSUE THREAD

**Issue by TalAter** [DAVFoundation/api_doc#27]
Rename `/source/dav-cli/user_guide.html.md` to `index.html.md` and then update the link on the homepage to simply point to `https://developers.dav.network/dav-cli/`

**Comment by JakePulis** [comment]
anyone doing this yet?

**Comment by cdt-eth** [comment]
Can I take this on?

**Comment by liorshkoori** [comment]
Sorry guys (@JakePulis @christiandavidturner ), we decided to to close this for the time being
